# Generated by Django 3.2.3 on 2021-05-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(default='receiver', max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
    ]
