# Generated by Django 3.2.3 on 2021-05-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usertype_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertype',
            old_name='address',
            new_name='information',
        ),
        migrations.AddField(
            model_name='usertype',
            name='donate_amount',
            field=models.CharField(default='', max_length=10),
        ),
    ]
