# Generated by Django 3.2.3 on 2021-05-23 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210523_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='donate_amount',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='information',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='mobile',
        ),
        migrations.CreateModel(
            name='DonatorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField()),
                ('donate_amount', models.CharField(default='', max_length=10)),
                ('donator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usertype')),
            ],
        ),
    ]
