# Generated by Django 3.2.3 on 2021-05-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210523_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatorinfo',
            name='blood_group',
            field=models.CharField(default='', max_length=2),
        ),
    ]
