# Generated by Django 3.2.3 on 2021-05-23 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_donatorinfo_blood_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.donatorinfo')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usertype')),
            ],
        ),
    ]
